version: "3.4"

services:
  deephaven:
    image: ghcr.io/deephaven/server:0.20.0
    ports:
      - "10000:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g -Ddeephaven.jsPlugins.resourceBase=/data/js-plugins